name: "Latex Build Action"
description: "Builds contents and homeworks of the SSW lectures and exercises"
inputs:
  python_version:
    description: "Python version to use"
    required: false
    default: "3.13"
  texlive_version:
    description: "TeX Live version to use"
    required: false
    default: "2024"
  texlive_packages:
    description: "TeX Live packages to install"
    required: false
    default: >-
      scheme-basic
  config_file_name:
    description: "Name of the configuration file"
    required: false
    default: .lecture-build-ci.json
  commit_user_name:
    description: "Name of the user who commits the changes"
    required: false
    default: LaTeX Exercise CI Build[bot]
  commit_user_email:
    description: "Email of the user who commits the changes"
    required: false
    default: latex-exercise-ci-bot@users.noreply.github.com
runs:
  using: "composite"
  steps:
    # Create symbolic link for requirements.txt (https://github.com/actions/setup-python/issues/361#issuecomment-2530429607)
    # to work around https://github.com/actions/setup-python/issues/361
    - name: Create symbolic link for requirements.txt
      run: ln -s ${{ github.action_path }}/requirements.txt
      shell: bash
    # install Python
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        cache: "pip" # caching pip dependencies
        python-version: ${{ inputs.python_version }}

    - name: Install Python dependencies
      working-directory: ${{ github.action_path }}
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade setuptools
        pip install -r requirements.txt

    # install TeX live + install required dependencies
    - name: Setup TeX Live
      uses: teatimeguest/setup-texlive-action@v3
      with:
        version: ${{ inputs.texlive_version }}
        # Any additionally required TeX packages should be placed here.
        # scheme-small could be used to provide more packages by default albeit with a larger download
        # tikz is part of pgf
        packages: ${{ inputs.texlive_packages }}

    # build all exercise and lecture files according to the script
    - name: Build exercises
      id: build-exercise-files
      run: ${{ github.action_path }}/run_action.sh
      shell: bash
      env:
        CONFIG_FILE: ${{ inputs.config_file_name }}
        GITHUB_ACTION_PATH: ${{ github.action_path }}

    # commit & push all changes (i.e. all generated PDFs, build logs)
    - uses: stefanzweifel/git-auto-commit-action@v4
      if: always()
      with:
        commit_message: Build TEX files

        # Optional glob pattern of files which should be added to the commit
        # Defaults to all (.)
        # See the `pathspec`-documentation for git
        # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
        # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
        file_pattern: "*/**/*.pdf */**/.checksum */**/*.build_log"

        # Optional commit user and author settings
        commit_user_name: ${{ inputs.commit_user_name }}
        commit_user_email: ${{ inputs.commit_user_email }}

        # Optional. Option used by `git-status` to determine if the repository is
        # dirty. See https://git-scm.com/docs/git-status#_options
        # status_options: '--untracked-files=no'

        # Optional. Options used by `git-add`.
        # See https://git-scm.com/docs/git-add#_options
        # add_options: "-u"

        # # Optional. Options used by `git-push`.
        # # See https://git-scm.com/docs/git-push#_options
        # push_options: "--force"

        # # Optional. Disable dirty check and always try to create a commit and push
        # skip_dirty_check: true

        # Optional. Skip internal call to `git fetch`
        skip_fetch: true

        # Optional. Skip internal call to `git checkout`
        skip_checkout: true

        # Optional. Prevents the shell from expanding filenames.
        # Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
        disable_globbing: true

        # # Optional. Create given branch name in local and remote repository.
        # create_branch: true
