name: LaTeX Build Action Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # checkout the repository
      - uses: actions/checkout@v4

      # install Python
      - uses: actions/setup-python@v5
        with:
          cache: "pip" # caching pip dependencies
          python-version: "3.13"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade setuptools
          pip install -r requirements.txt

      # install TeX live + install required dependencies
      - name: Setup TeX Live
        uses: teatimeguest/setup-texlive-action@v3
        with:
          version: "2024"
          packages: >-
            scheme-basic
            latexmk

      - name: Lint
        run: make lint

      - name: Type check
        run: make typecheck

      - name: Run unittests
        run: make test
